{% set version = "1.13.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-biodivmapr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://github.com/jbferet/biodivMapR/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 087d248d37a08ed95aa0356c7213b5dc94aacf4eabbb45fc66cbf9de54d41056

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ape
    - r-cli
    - r-dissutils
    - r-data.table
    - r-fields
    - r-future
    - r-future.apply
    - r-geometry
    - r-labdsv
    - r-matlab
    - r-matrixStats
    - r-mmand
    - r-progressr
    - r-raster
    - r-rgdal
    - r-snow
    - r-stars
    - r-stringr
    - r-terra
    - r-vegan
    - r-zip
  run:
    - r-base
    - r-ape
    - r-cli
    - r-dissutils
    - r-data.table
    - r-fields
    - r-future
    - r-future.apply
    - r-geometry
    - r-labdsv
    - r-matlab
    - r-matrixStats
    - r-mmand
    - r-progressr
    - r-raster
    - r-rgdal
    - r-snow
    - r-stars
    - r-stringr
    - r-terra
    - r-vegan
    - r-zip

test:
  commands:
    - $R -e "library('biodivMapR')"           # [not win]
    - "\"%R%\" -e \"library('biodivMapR')\""  # [win]

about:
  home: https://jbferet.github.io/biodivMapR/
  dev_url: https://github.com/jbferet/biodivMapR
  doc_url: https://jbferet.github.io/biodivMapR/reference/index.html
  license: GPL-3.0-only
  summary: An R package for α- and β-diversity mapping using remotely-sensed images
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
