{% set version = '1.9.8' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-biodivmapr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://github.com/jbferet/biodivMapR/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 066d0678e77288e35cb44064da7e0114f8b811446c1adb3b401df48da0ee551e

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-remotes
    - r-dissutils
    - r-data.table
    - r-emstreer
    - r-fields
    - r-future
    - r-future.apply
    - r-geometry
    - r-labdsv
    - r-matlab
    - r-matrixStats
    - r-mmand
    - r-raster
    - r-rgdal
    - r-R.utils
    - r-snow
    - r-sp
    - r-stars
    - r-stringr
    - r-vegan
    - r-zip
    - r-sf
    - r-rgeos
    - r-progress
    - r-progressr
  run:
    - r-base
    - r-remotes
    - r-dissutils
    - r-data.table
    - r-emstreer
    - r-fields
    - r-future
    - r-future.apply
    - r-geometry
    - r-labdsv
    - r-matlab
    - r-matrixStats
    - r-mmand
    - r-raster
    - r-rgdal
    - r-R.utils
    - r-snow
    - r-sp
    - r-stars
    - r-stringr
    - r-vegan
    - r-zip
    - r-sf
    - r-rgeos
    - r-progress
    - r-progressr
test:
  commands:
    - $R -e "library('biodivMapR')"           # [not win]
    - "\"%R%\" -e \"library('biodivMapR')\""  # [win]

about:
  home: https://github.com/jbferet/biodivMapR
  license: GPL-3.0-only
  summary: 'An R package for α- and β-diversity mapping using remotely-sensed images'
  license_family: GPL3
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
